server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/early
    driver-class-name: org.mariadb.jdbc.Driver
    username: early
    password: early

  redis:    
    port: 6379 
    host: 127.0.0.1   
   
  mvc :
    view : 
        suffix: .html
     
  config:
    import:
    - serverConfig.yml
        

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
  
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 917660405716-5mdk8ab542luosidsriaijp46e5d174f.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google



     
