server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/early
    driver-class-name: org.mariadb.jdbc.Driver
    username: early
    password: early

  redis:    
    port: 6379 
    host: 127.0.0.1   
  

  mvc :
    view : 
        suffix: .html
        

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    
  

    
    
   
